const grounds={v:ground('v'),f:ground('f')};
function draw(){x.imageSmoothingEnabled=false;let cx=Math.max(0,Math.min(320,p.x-320)),cy=Math.max(0,Math.min(180,p.y-180));x.save();x.scale(2,2);x.translate(-Math.round(cx),-Math.round(cy));x.drawImage(grounds[p.map],0,0);let z=maps[p.map].portal;x.fillStyle='#acc5a080';x.fillRect(z[0],z[1],z[2],z[3]);x.fillStyle='#fff0ca';x.font='10px Tahoma';x.textAlign='center';x.fillText(p.map==='v'?'↓ SLIME MEADOW':'↑ WILLOWBROOK',480,p.map==='v'?500:24);
let rows=World.objects[p.map].map(o=>{let a=Art.object(o[0]);return{y:o[2]+a.height,draw:()=>x.drawImage(a,o[1],o[2])}});
for(let n of maps[p.map].npcs)rows.push({y:n[3]+20,draw:()=>{x.drawImage(Art.actor(n[0],'down',Math.floor(elapsed*2)%2),n[2]-32,n[3]-40);x.font='10px Tahoma';x.lineWidth=3;x.strokeStyle='#263d35';x.fillStyle='#fff3d4';x.strokeText(n[1],n[2],n[3]-48);x.fillText(n[1],n[2],n[3]-48);if(Math.hypot(p.x-n[2],p.y-n[3])<70){x.fillStyle='#21333b';x.fillRect(n[2]-22,n[3]-71,44,16);x.fillStyle='#f3d89d';x.fillText('กด E',n[2],n[3]-59)}}});
for(let m of mobs)if(!m.dead)rows.push({y:m.y+12,draw:()=>{x.globalAlpha=m.flash?.45:1;x.drawImage(Art.slime(Math.floor(elapsed*5+m.t)%4),m.x-24,m.y-24);x.globalAlpha=1;if(m.hp<3){x.fillStyle='#253b35';x.fillRect(m.x-16,m.y-31,32,4);x.fillStyle='#cb8b79';x.fillRect(m.x-15,m.y-30,30*m.hp/3,2)}}});
rows.push({y:p.y+20,draw:()=>{x.globalAlpha=p.hit&&Math.floor(p.hit*15)%2?.5:1;x.drawImage(Art.actor('player',facing,walking?Math.floor(elapsed*9)%4:0,p.cd>.15),p.x-32,p.y-40);x.globalAlpha=1}});rows.sort((a,b)=>a.y-b.y).forEach(r=>r.draw());
for(let e of effects){if(e.type==='damage'){x.fillStyle=e.text==='1'?'#fff0b0':'#ffc5b4';x.font='bold 14px Tahoma';x.strokeStyle='#303f38';x.lineWidth=3;x.strokeText(e.text,e.x,e.y-(.7-e.life)*25);x.fillText(e.text,e.x,e.y-(.7-e.life)*25)}else if(e.type==='swing'){x.strokeStyle='#fff1c0';x.lineWidth=3;x.beginPath();let a={down:0,up:Math.PI,left:Math.PI/2,right:-Math.PI/2}[facing];x.arc(e.x,e.y,33,a,a+Math.PI);x.stroke()}else{ x.globalAlpha=e.life/.55;x.drawImage(Art.slime(0),e.x-24,e.y-24-(.55-e.life)*20);x.fillStyle='#e3d8a1';for(let i=0;i<6;i++)x.fillRect(e.x+Math.cos(i)*(.55-e.life)*50,e.y+Math.sin(i)*(.55-e.life)*50,3,3);x.globalAlpha=1}}
x.restore();document.getElementById('level').textContent='Lv. '+p.lv;document.getElementById('hpbar').style.width=100*p.hp/p.max+'%';document.getElementById('expbar').style.width=100*p.exp/p.next+'%';document.getElementById('hptext').textContent=p.hp+' / '+p.max+' HP';document.getElementById('exptext').textContent=p.exp+' / '+p.next+' EXP';document.getElementById('location').textContent=p.map==='v'?'Willowbrook · หมู่บ้านริมธาร':'Slime Meadow · ทุ่งหญ้าสไลม์';}

