const grounds={v:ground('v'),f:ground('f')};
function draw(){x.globalAlpha=1;x.imageSmoothingEnabled=false;let camera=cameraPosition(),cx=camera.x,cy=camera.y;x.save();x.scale(c.width/World.viewW,c.height/World.viewH);x.translate(-Math.round(cx),-Math.round(cy));x.drawImage(grounds[p.map],0,0);let z=maps[p.map].portal;x.fillStyle='#acc5a080';x.fillRect(z[0],z[1],z[2],z[3]);x.fillStyle='#fff0ca';x.font='10px Tahoma';x.textAlign='center';x.fillText(p.map==='v'?'↓ SLIME MEADOW':'↑ WILLOWBROOK',480,p.map==='v'?500:24);
if(walkTarget){x.strokeStyle='#f3df9f';x.lineWidth=1;x.beginPath();x.ellipse(walkTarget.x,walkTarget.y,9,4,0,0,Math.PI*2);x.stroke();x.fillStyle='#f3df9f';x.fillRect(walkTarget.x-1,walkTarget.y-2,2,4);}
// Gentle pollen and actor contact shadows: a few primitives, no shaders.
for(let i=0;i<12;i++){const X=(i*83+Math.sin(elapsed*.2+i)*12)%960,Y=(i*61+elapsed*3)%540;x.fillStyle='#f4e7b340';x.fillRect(X,Y,1,1)}
x.fillStyle='#344a3b55';x.beginPath();x.ellipse(p.x,p.y+18,16,5,0,0,Math.PI*2);x.fill();
for(const n of maps[p.map].npcs){x.beginPath();x.ellipse(n[2],n[3]+20,15,4,0,0,Math.PI*2);x.fill()}
let rows=World.objects[p.map].map(o=>{let a=Art.object(o[0]);return{y:o[2]+a.height,draw:()=>x.drawImage(a,o[1],o[2])}});
for(let n of maps[p.map].npcs)rows.push({y:n[3]+20,draw:()=>{x.drawImage(Art.actor(n[0],'down',elapsed%5<.13?1:elapsed%5<2.5?0:2),n[2]-32,n[3]-40);x.font='10px Tahoma';x.lineWidth=3;x.strokeStyle='#263d35';x.fillStyle='#fff3d4';x.strokeText(n[1],n[2],n[3]-48);x.fillText(n[1],n[2],n[3]-48);if(Math.hypot(p.x-n[2],p.y-n[3])<70){x.fillStyle='#21333b';x.fillRect(n[2]-22,n[3]-71,44,16);x.fillStyle='#f3d89d';x.fillText('กด E',n[2],n[3]-59)}}});
for(let m of mobs)if(!m.dead)rows.push({y:m.y+12,draw:()=>{x.globalAlpha=m.flash?.45:1;x.drawImage(monsterSprite(m,Math.floor(elapsed*6+m.t)%4),m.x-24,m.y-(m.kind==='boar'?24:32));x.globalAlpha=1;x.font='9px Tahoma';x.fillStyle=combatTarget===m?'#ffe0a2':'#fff4d5';x.strokeStyle='#263d35';x.lineWidth=2;x.strokeText(m.name+' Lv.'+m.level,m.x,m.y-35);x.fillText(m.name+' Lv.'+m.level,m.x,m.y-35);if(m.hp<m.maxHp){x.fillStyle='#253b35';x.fillRect(m.x-16,m.y-31,32,4);x.fillStyle='#cb8b79';x.fillRect(m.x-15,m.y-30,30*m.hp/m.maxHp,2)}}});
rows.push({y:p.y+20,draw:()=>{x.save();x.globalAlpha=1;x.drawImage(Art.actor('player',facing,walking?Math.floor(elapsed*10)%8:0,p.cd>0),p.x-32,p.y-40);if(p.hit>0&&Math.floor(p.hit*15)%2===1){x.strokeStyle='#ed9986';x.lineWidth=2;x.beginPath();x.ellipse(p.x,p.y+18,18,7,0,0,Math.PI*2);x.stroke()}x.restore()}});rows.sort((a,b)=>a.y-b.y).forEach(r=>r.draw());
for(let e of effects){if(e.type==='damage'){x.fillStyle=!e.text.startsWith('-')?'#fff0b0':'#ffc5b4';x.font='bold 14px Tahoma';x.strokeStyle='#303f38';x.lineWidth=3;x.strokeText(e.text,e.x,e.y-(.7-e.life)*25);x.fillText(e.text,e.x,e.y-(.7-e.life)*25)}else if(e.type==='swing'){const progress=1-e.life/.25;
let a={down:Math.PI/2,up:-Math.PI/2,left:Math.PI,right:0}[facing];
x.globalAlpha=Math.max(0,1-progress*.8);
for(let band=0;band<3;band++){x.strokeStyle=['#d4b66c','#f6dfa0','#fff9d5'][band];x.lineWidth=5-band;x.beginPath();x.arc(e.x,e.y,29+band*3,a-.95+progress*.5,a+.65+progress*.5);x.stroke()}
x.globalAlpha=1;}else{ x.globalAlpha=e.life/.55;x.drawImage(e.kind==='boar'?monsterSprite({kind:'boar'},0):Art.slime(Math.min(3,Math.floor((.55-e.life)/.55*4)),'death'),e.x-24,e.y-32);x.fillStyle='#e3d8a1';for(let i=0;i<6;i++)x.fillRect(e.x+Math.cos(i)*(.55-e.life)*50,e.y+Math.sin(i)*(.55-e.life)*50,3,3);x.globalAlpha=1}}
x.restore();document.getElementById('level').textContent='Lv. '+p.lv+' · ATK '+playerAttack();document.getElementById('hpbar').style.width=100*p.hp/p.max+'%';document.getElementById('expbar').style.width=100*p.exp/p.next+'%';document.getElementById('hptext').textContent=p.hp+' / '+p.max+' HP';document.getElementById('exptext').textContent=p.exp+' / '+p.next+' EXP';document.getElementById('location').textContent=p.map==='v'?'Willowbrook · หมู่บ้านริมธาร':'Slime Meadow · ทุ่งหญ้าสไลม์';}


// Start only after navigation, monster art and rendering are ready.
Painted.ready.then(()=>{grounds.v=ground('v');grounds.f=ground('f');last=performance.now();requestAnimationFrame(loop)}).catch(error=>{document.getElementById('combat-status').textContent='โหลดภาพไม่สำเร็จ กรุณารีเฟรช';console.error(error)});
